# Generated by Django 3.2.5 on 2021-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('signature', models.ImageField(upload_to='', verbose_name='Signature')),
            ],
        ),
    ]
