# Generated by Django 3.2.5 on 2021-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='lname',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Last Name'),
        ),
    ]
