# Generated by Django 3.2.5 on 2021-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature_app', '0002_auto_20211202_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='signature',
            field=models.ImageField(upload_to='customers'),
        ),
    ]
